Repository spo-kissa/spoclient, pull requests merged in 2025-04, with the labels that each got.

#24 設定のマイグレーションなどに対応中
  SpoClient.Setting/Migrator.cs
  SpoClient.Setting/SQLite.cs
  SpoClient.Setting/SecureStringExtensions.cs
  SpoClient.Setting/Servers/Migrations/0001_create_servers.sql
  SpoClient.Setting/Settings.cs
  SpoClient.Setting/SpoClient.Setting.csproj
  SpoClient.Setting/SqlMigration.cs
  SpoClient.Setting/SqlResourceLoader.cs
  SpoClient.Setting/SqliteConnectionExtensions.cs
  spoclient.sln
  spoclient/Assets/icon.ico
  spoclient/Models/SecureServerInfo.cs
  spoclient/Models/ServerInfo.cs
  spoclient/Models/ServerSettingsRepository.cs
  spoclient/ViewModels/ServerDialogViewModel.cs
  spoclient/Views/AboutDialog.axaml
  spoclient/Views/MainAppSplashContent.axaml
  spoclient/Views/MainAppSplashContent.axaml.cs
  spoclient/Views/MainView.axaml
  spoclient/Views/MainWindow.axaml
  spoclient/spoclient.csproj
Labels: enhancement

#26 Fix: Cound not find file 'spoclient.setting'.
  SpoClient.Setting/SQLite.cs
Labels: bug

#27 Dialog title applied
  spoclient/ViewModels/AboutDialogViewModel.cs
  spoclient/ViewModels/MainViewViewModel.cs
  spoclient/ViewModels/ServerDialogViewModel.cs
  spoclient/ViewModels/ServersDialogViewModel.cs
  spoclient/ViewModels/ViewModelBase.cs
  spoclient/Views/DialogWindow.axaml
Labels: enhancement

#28 Disabled splash screen animation.
  SpoClient.Setting/SQLite.cs
  spoclient/Views/MainAppSplashContent.axaml
  spoclient/Views/MainAppSplashContent.axaml.cs
Labels: bug

#29 Localization
  SpoClient.Localization/Localizer.cs
  SpoClient.Localization/Resources/Strings.Designer.cs
  SpoClient.Localization/Resources/Strings.ja.resx
  SpoClient.Localization/Resources/Strings.resx
  SpoClient.Localization/SpoClient.Localization.csproj
  SpoClient.Setting/Models/SecureServer.cs
  SpoClient.Setting/Models/Server.cs
  SpoClient.Setting/Repositories/Servers.cs
  SpoClient.Setting/Servers/Migrations/0002_alter_entry_to_name_servers.sql
  SpoClient.Setting/Servers/Migrations/0003_alter_server_to_host_servers.sql
  SpoClient.Setting/Settings.cs
  SpoClient.Setting/SpoClient.Setting.csproj
  spoclient.sln
  spoclient/App.axaml.cs
  spoclient/Models/SecureServerInfo.cs
  spoclient/Models/ServerInfo.cs
  spoclient/Models/ServerSettingsRepository.cs
  spoclient/Program.cs
  spoclient/Service/SshService.cs
  spoclient/Terminals/SshConnection.cs
  spoclient/ViewModels/HomePageViewModel.cs
  spoclient/ViewModels/MainViewViewModel.cs
  spoclient/ViewModels/ServerDialogViewModel.cs
  spoclient/ViewModels/ServersDialogViewModel.cs
  spoclient/ViewModels/ShellTabViewViewModel.cs
  spoclient/Views/MainView.axaml
  spoclient/Views/ServerDialog.axaml
  spoclient/Views/ServersDialog.axaml
  spoclient/spoclient.csproj
Labels: enhancement

#31 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#32 Update issue templates
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#33 Update issue templates
  .github/ISSUE_TEMPLATE/custom.md
Labels: documentation

#35 The application settings have been integrated into SQLite.
  SpoClient.Setting/Models/AppSettingKeys.cs
  SpoClient.Setting/Models/AppSettings.cs
  SpoClient.Setting/Models/IAppSettings.cs
  SpoClient.Setting/Models/SecureServer.cs
  SpoClient.Setting/Models/Setting.cs
  SpoClient.Setting/Repositories/Settings.cs
  SpoClient.Setting/SQL/Migrations/0001_create_servers.sql
  SpoClient.Setting/SQL/Migrations/0002_alter_entry_to_name_servers.sql
  SpoClient.Setting/SQL/Migrations/0003_alter_server_to_host_servers.sql
  SpoClient.Setting/SQL/Migrations/0004_create_table_settings.sql
  SpoClient.Setting/SettingManager.cs
  SpoClient.Setting/SpoClient.Setting.csproj
  spoclient/App.axaml.cs
  spoclient/Program.cs
  spoclient/ViewModels/ServersDialogViewModel.cs
  spoclient/Views/MainAppSplashContent.axaml.cs
Labels: enhancement

#39 Fix the timing of the database migration.
  spoclient/App.axaml.cs
  spoclient/Plugins/Recipe/RecipeV1Loader.cs
  spoclient/Views/MainAppSplashContent.axaml.cs
Labels: bug

#34 Static localization example
  SpoClient.Localization/Resources/Strings.Designer.cs
  SpoClient.Localization/Resources/Strings.ja.resx
  SpoClient.Localization/Resources/Strings.resx
  SpoClient.Localization/SpoClient.Localization.csproj
  spoclient/App.axaml.cs
  spoclient/LocalizationForXaml/StaticLocalizationSettings.cs
  spoclient/LocalizationForXaml/TranslateExtension.cs
  spoclient/ViewModels/MainViewViewModel.cs
  spoclient/Views/MainView.axaml
  spoclient/spoclient.csproj
Labels: enhancement

#40 Namespace changes and minor fixes.
  spoclient/App.axaml.cs
  spoclient/LocalizationForXaml/StaticLocalizationSettings.cs
  spoclient/Service/SshService.cs
  spoclient/Views/Extensions/TranslateExtension.cs
  spoclient/Views/MainView.axaml
Labels: enhancement

#42 Mod env
  .github/pull_request_template.md
  CONTRIBUTING.md
  LICENSE.txt
  README.md
Labels: documentation

#43 Translations for the words
  SpoClient.Localization/Resources/Strings.Designer.cs
  SpoClient.Localization/Resources/Strings.ja.resx
  SpoClient.Localization/Resources/Strings.resx
  SpoClient.Localization/SpoClient.Localization.csproj
  spoclient/ViewModels/AboutDialogViewModel.cs
  spoclient/ViewModels/MainViewViewModel.cs
  spoclient/Views/MainView.axaml
  spoclient/Views/ServerDialog.axaml
  spoclient/Views/ServersDialog.axaml
Labels: enhancement

#46 Fix design view error
  SpoClient.Localization/Resources/Strings.ru.resx
  spoclient/Views/Extensions/TranslateExtension.cs
  spoclient/Views/ServersDialog.axaml
Labels: bug

#47 Add language menu checkmark.
  SpoClient.Localization/Resources/Strings.Designer.cs
  SpoClient.Localization/Resources/Strings.ja.resx
  SpoClient.Localization/Resources/Strings.resx
  SpoClient.Localization/Resources/Strings.ru.resx
  spoclient/ViewModels/MainViewViewModel.cs
  spoclient/Views/Extensions/CurrentCultureToBoolConverter.cs
  spoclient/Views/MainAppSplashContent.axaml.cs
  spoclient/Views/MainView.axaml
Labels: enhancement
